version: '3.8'

services:
  server:
    build: .
    container_name: consensus-server
    command: gunicorn --bind 0.0.0.0:5000 app:app
    # No es necesario aquí, ya que gunicorn maneja sus propios logs.
    networks:
      - consensus-net

  agent-0:
    build: .
    command: python agent.py
    environment:
      - AGENT_ID=0
      - PYTHONUNBUFFERED=1 # <-- AÑADE ESTA LÍNEA
    depends_on:
      - server
    networks:
      - consensus-net

  agent-1:
    build: .
    command: python agent.py
    environment:
      - AGENT_ID=1
      - PYTHONUNBUFFERED=1 # <-- AÑADE ESTA LÍNEA
    depends_on:
      - server
    networks:
      - consensus-net

  agent-2:
    build: .
    command: python agent.py
    environment:
      - AGENT_ID=2
      - PYTHONUNBUFFERED=1 # <-- AÑADE ESTA LÍNEA
    depends_on:
      - server
    networks:
      - consensus-net
  
  observer:
    build: .
    command: sh -c "sleep 5 && python observer.py"
    environment:
      - PYTHONUNBUFFERED=1 # <-- AÑADE ESTA LÍNEA
    depends_on:
      - server
    networks:
      - consensus-net

networks:
  consensus-net:
    driver: bridge